name: Docker Compose Actions Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build project 
      run: docker-compose -f docker-compose.yml up -d
    - name: Test
      run: docker run --network container:SBMongoApp appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/
